"""Export item-bank JSON into a browser-loadable JavaScript bundle."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ITEM_BANK = ROOT / "item_bank"
WEB_DIR = ROOT / "web"


def main() -> None:
    chapters = []
    for path in sorted(ITEM_BANK.glob("chapter_*.json")):
        chapters.append(json.loads(path.read_text(encoding="utf-8")))

    WEB_DIR.mkdir(exist_ok=True)
    payload = json.dumps(chapters, ensure_ascii=False, indent=2)
    content = (
        "/* Generated by tools/export_web_items.py. Do not edit by hand. */\n"
        f"window.SCHOLARFIT_ITEM_BANK = {payload};\n"
    )
    (WEB_DIR / "items.generated.js").write_text(content, encoding="utf-8")
    print(f"Exported {len(chapters)} chapters to {WEB_DIR / 'items.generated.js'}")


if __name__ == "__main__":
    main()
